// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System;
using System.Collections.Generic;
using Azure.Core;

namespace Azure.Messaging.WebPubSub
{
    /// <summary> Client options for WebPubSubServiceClient. </summary>
    public partial class WebPubSubServiceClientOptions : ClientOptions
    {
        /// <summary>
        /// Reverse proxy.
        /// </summary>
        public Uri ReverseProxyEndpoint { get; set; }

        /// <summary>
        /// AllowedHosts for abuse protection validation.
        /// </summary>
        public List<string> AllowedHosts { get; set; }

        /// <summary>
        /// AccessKeys for Signature checks.
        /// </summary>
        public List<string> AccessKeys { get; set; }
    }
}
